# ========================
# Spring Config
# ========================
spring.application.name=todo

# ========================
# MySQL
# ========================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create-drop
debug=true

# ========================
# Judge0Client
# ========================

external.judge0.url=${JUDGE_URL}

# ========================
# Redis
# ========================

spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}

# ========================
# JWT
# ========================
jwt.secret=${JWT_SECRET}

# ========================
# Swagger
# ========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

# ========================
# ActiveMQ
# ========================
spring.message.activemq.address=${ACTIVEMQ_ADDRESS}
spring.message.activemq.username=${ACTIVEMQ_USER}
spring.message.activemq.password=${ACTIVEMQ_PASSWORD}
spring.message.activemq.port=${ACTIVEMQ_PORT}

# ========================
# Actuator
# ========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
